#!/usr/bin/env python3
"""
Summarize artifacts/cooperative_pairs_with_flag_gear.csv for reports and slides.

Outputs:
- Console summary
- Optional Markdown file (tables: MID same/cross, gear pairs, coverage)
- Optional JSON for tooling

Requires: pandas (see requirements.txt).
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd

DEFAULT_INPUT = Path("artifacts/cooperative_pairs_with_flag_gear.csv")
DEFAULT_OUT_MD = Path("artifacts/flag_gear_enrichment_summary.md")
DEFAULT_OUT_JSON = Path("artifacts/flag_gear_enrichment_summary.json")


def _fill_gear(s: pd.Series) -> pd.Series:
    return s.fillna("").astype(str).str.strip().replace("", "(missing)")


def summarize(df: pd.DataFrame) -> dict:
    n = len(df)
    out: dict = {"n_rows": n, "columns": list(df.columns)}

    if "src_mid" in df.columns and "dst_mid" in df.columns:
        same = (df["src_mid"] == df["dst_mid"]).sum()
        out["mid_same_count"] = int(same)
        out["mid_cross_count"] = int(n - same)
        out["mid_same_pct"] = round(100.0 * same / n, 1) if n else 0.0

    if "src_gear" in df.columns and "dst_gear" in df.columns:
        sg = _fill_gear(df["src_gear"])
        dg = _fill_gear(df["dst_gear"])
        both = (sg != "(missing)") & (dg != "(missing)")
        out["gear_both_present"] = int(both.sum())
        out["gear_either_missing"] = int((~both).sum())

        combo = sg + " → " + dg
        vc = combo.value_counts()
        out["gear_pair_counts"] = {k: int(v) for k, v in vc.head(15).items()}
        out["same_gear_count"] = int((sg == dg).sum())
        out["same_gear_both_nonmissing"] = int(((sg == dg) & both).sum())

    if "label" in df.columns and "src_mid" in df.columns:
        for lab, g in df.groupby("label"):
            key = f"label_{lab}_mid_same"
            if len(g):
                out[key] = int((g["src_mid"] == g["dst_mid"]).sum())

    if "src_flag_cell" in df.columns and "dst_flag_cell" in df.columns:
        sf = _fill_gear(df["src_flag_cell"])
        df2 = _fill_gear(df["dst_flag_cell"])
        both_f = (sf != "(missing)") & (df2 != "(missing)")
        out["flag_cell_both_present"] = int(both_f.sum())

    return out


def render_markdown(df: pd.DataFrame, stats: dict) -> str:
    lines = [
        "# Flag / gear enrichment summary",
        "",
        f"**Source:** `{DEFAULT_INPUT}`  ",
        f"**Rows:** {stats.get('n_rows', len(df))}",
        "",
    ]

    if "mid_same_count" in stats:
        lines.extend(
            [
                "## Maritime Identification Digits (MID)",
                "",
                "| Category | Count | % of rows |",
                "|----------|-------|-----------|",
                f"| Same MID (`src_mid` == `dst_mid`) | {stats['mid_same_count']} | {stats.get('mid_same_pct', 0)}% |",
                f"| Different MID | {stats['mid_cross_count']} | {round(100.0 - stats.get('mid_same_pct', 0), 1)}% |",
                "",
            ]
        )

    if "gear_both_present" in stats:
        lines.extend(
            [
                "## Gear attribution (hours-weighted)",
                "",
                f"- Rows with **both** `src_gear` and `dst_gear`: **{stats['gear_both_present']}**",
                f"- Rows with **missing** gear on either side: **{stats['gear_either_missing']}**",
                f"- Rows with **same** geartype string on both sides (including both missing): **{stats.get('same_gear_count', 'n/a')}**",
        f"- Rows with **same** geartype with **both** sides non-missing: **{stats.get('same_gear_both_nonmissing', 'n/a')}**",
                "",
            ]
        )

    if stats.get("gear_pair_counts"):
        lines.extend(["### Most common `src_gear → dst_gear` pairs", "", "| Rank | Pair | Count |", "|------|------|-------|"])
        for i, (pair, cnt) in enumerate(stats["gear_pair_counts"].items(), 1):
            lines.append(f"| {i} | `{pair}` | {cnt} |")
        lines.append("")

    if "label_0_mid_same" in stats or "label_1_mid_same" in stats:
        lines.extend(
            [
                "## By TGCN bucket label (if present)",
                "",
                "| label | same-MID pairs (count) |",
                "|-------|-------------------------|",
            ]
        )
        for lab in sorted(df["label"].unique()) if "label" in df.columns else []:
            k = f"label_{lab}_mid_same"
            if k in stats:
                lines.append(f"| {lab} | {stats[k]} |")
        lines.append("")

    lines.extend(
        [
            "---",
            "",
            "*Generated by `scripts/summarize_flag_gear_enrichment.py`.*",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description="Summarize flag/gear enrichment CSV.")
    ap.add_argument("--input", type=Path, default=DEFAULT_INPUT, help="Enriched pairs CSV")
    ap.add_argument("--out-md", type=Path, default=DEFAULT_OUT_MD, help="Write Markdown summary")
    ap.add_argument("--out-json", type=Path, default=DEFAULT_OUT_JSON, help="Write JSON stats")
    ap.add_argument("--no-files", action="store_true", help="Print only; do not write files")
    args = ap.parse_args()

    if not args.input.exists():
        raise SystemExit(f"Input not found: {args.input}")

    df = pd.read_csv(args.input)
    stats = summarize(df)

    # Console
    print(f"Rows: {stats['n_rows']}")
    if "mid_same_count" in stats:
        print(
            f"  Same MID: {stats['mid_same_count']} ({stats['mid_same_pct']}%)  "
            f"Different MID: {stats['mid_cross_count']}"
        )
    if "gear_both_present" in stats:
        print(
            f"  Gear both present: {stats['gear_both_present']}  "
            f"Either missing: {stats['gear_either_missing']}  "
            f"Same gear (incl. both missing): {stats.get('same_gear_count', 'n/a')}  "
            f"Same gear (both non-missing): {stats.get('same_gear_both_nonmissing', 'n/a')}"
        )
    if stats.get("gear_pair_counts"):
        print("  Top gear pairs:")
        for pair, cnt in list(stats["gear_pair_counts"].items())[:5]:
            print(f"    {pair}: {cnt}")

    if not args.no_files:
        args.out_md.parent.mkdir(parents=True, exist_ok=True)
        md = render_markdown(df, stats)
        args.out_md.write_text(md, encoding="utf-8")
        print(f"Wrote {args.out_md}")
        with open(args.out_json, "w", encoding="utf-8") as f:
            # Drop large nested if any
            j = {k: v for k, v in stats.items() if k != "gear_pair_counts"}
            j["gear_pair_counts"] = stats.get("gear_pair_counts", {})
            json.dump(j, f, indent=2)
        print(f"Wrote {args.out_json}")


if __name__ == "__main__":
    main()
